### ISSUE TITLE
Link in emails send out to teachers is not working

### ISSUE THREAD

**Issue by RachL** [orzubalsky/tradeschool#114]
Hi Or,

When a Teacher adds a class, he receives an email with a link created thanks to  {{ class_edit_url }} that enables him to edit his or her class info.

I've tested the system with a bogus class and the email shows me this link:

http://tradeschool.coop/paris/class/ceci-est-un-test/edit

which does not work.

**Comment by orzubalsky** [comment]
1d15695baa5d82d30c4949070c0a75193fb54b29

Good catch, thank you! It's fixed now.

**Comment by RachL** [comment]
Thanks Or :)

**Comment by RachL** [comment]
Hi Or,

It seems that the bug is back again. here is the message that teacher see after clicking on the link:
http://awesomescreenshot.com/0692dimd76

**Comment by orzubalsky** [comment]
This is strange. The URL was missing "-1" at the end, but I'm not sure why this happened. Can you let me know if this happens again? I can't seem to reproduce the problem.

Also, if it happens again, you can find the class on the admin backend and look at the URL slug field to make sure it's the same as in the url.

**Comment by RachL** [comment]
Thanks :-)
